# Generated by Django 3.2.20 on 2026-02-28 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('application_id', models.CharField(max_length=50, unique=True)),
                ('applying_for_class', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=30)),
                ('parent_first_name', models.CharField(max_length=100)),
                ('parent_last_name', models.CharField(max_length=100)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('current_class', models.CharField(max_length=50)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('enrolled_active', 'Enrolled - Active'), ('suspended', 'Suspended'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated')], default='enrolled_active', max_length=30)),
                ('application', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_lifecycle.application')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
